CREATE TABLE IF NOT EXISTS appointment (
	id SERIAL PRIMARY KEY,
	appt_date TIMESTAMP NOT NULL,
	subject VARCHAR(50) NOT NULL,
	user_id   INT8 NOT NULL,
	CONSTRAINT fk_appt_user FOREIGN KEY(user_id) REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE
);